trigger:
  - master  # or your main branch name

pool:
  vmImage: 'ubuntu-latest'

steps:
  - checkout: self

  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean compile'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.21'
      mavenVersionOption: 'Default'
      publishJUnitResults: true
      testResultsFiles: '**/TEST-*.xml'
